#!/usr/bin/env node
// Generate a promotion-plan skeleton from a Flatpack.
//
// Reads the Flatpack's inline manifest and emits a markdown plan
// pre-filled with every MANIFEST-ASSERTED claim. Leaves CODE-INFERRED
// and INTERVIEW-REQUIRED sections as labelled placeholders.
//
// Usage:
//   node tools/promote.mjs path/to/flatpack.html              # to stdout
//   node tools/promote.mjs path/to/flatpack.html --out plan.md # to file
//
// The script is deliberately NOT smart. It does not try to walk the
// JS to infer entities or answer questions for the user — that would
// defeat the purpose of the three confidence tiers. The agent reading
// the prompt still does the CODE-INFERRED and INTERVIEW-REQUIRED work.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

function readManifest(filePath) {
  const html = fs.readFileSync(filePath, "utf8");
  const m = html.match(/<script\s+type="application\/json"\s+id="flatpack-manifest">([\s\S]*?)<\/script>/);
  if (!m) throw new Error(`No <script type="application/json" id="flatpack-manifest"> block in ${filePath}`);
  try {
    return JSON.parse(m[1]);
  } catch (e) {
    throw new Error(`Manifest in ${filePath} is not valid JSON: ${e.message}`);
  }
}

function renderEntity(entity) {
  const fields = (entity.fields || []).map(f => {
    const constraints = [];
    if (f.required) constraints.push("required");
    if (f.unique) constraints.push("unique");
    if (f.default !== undefined) constraints.push(`default ${JSON.stringify(f.default)}`);
    if (f.min !== undefined) constraints.push(`>= ${f.min}`);
    if (f.max !== undefined) constraints.push(`<= ${f.max}`);
    if (f.gt !== undefined) constraints.push(`> ${f.gt}`);
    if (f.values) constraints.push(`one of [${f.values.join(", ")}]`);
    if (f.ref) constraints.push(`ref → ${f.ref}`);
    if (f.warnIfNotIn) constraints.push(`warn if not in [${f.warnIfNotIn.join(", ")}]`);
    if (f.constraint) constraints.push(f.constraint);
    if (f.note) constraints.push(`(${f.note})`);
    const cs = constraints.length ? `; ${constraints.join("; ")}` : "";
    return `- \`${f.name}\` — ${f.type}${cs}`;
  });
  return [
    `### \`${entity.name}\` **MANIFEST-ASSERTED**`,
    "",
    "Fields:",
    "",
    ...fields,
    "",
    "Relations: <!-- CODE-INFERRED: any FK references the manifest didn't declare? -->",
    "Indexes / uniques: <!-- CODE-INFERRED: derive from unique fields above -->",
  ].join("\n");
}

function renderPlan(manifest, sourcePath) {
  const today = new Date().toISOString().slice(0, 10);
  const archetype = manifest.archetype || "(none — manifest does not declare one)";
  const entities = manifest.entities || [];
  const validations = manifest.validations || [];
  const predicates = manifest.validation_predicates || [];
  const exports_ = manifest.exports || [];
  const imports = manifest.imports || [];
  const signals = manifest.promotionSignals || [];

  const entityBlock = entities.length
    ? entities.map(renderEntity).join("\n\n")
    : "<!-- MANIFEST has no entities declared. CODE-INFERRED: walk SCHEMA. -->";

  const validationBlock = validations.length
    ? validations.map(v => `- ${v} **MANIFEST-ASSERTED**`).join("\n")
    : "<!-- MANIFEST has no validations declared. CODE-INFERRED: walk VALIDATION. -->";

  const predicateBlock = predicates.length
    ? predicates
        .map(p => {
          const v = p.value !== undefined ? ` ${JSON.stringify(p.value)}` : "";
          const desc = p.description ? `  _${p.description}_` : "";
          return `- \`${p.field}\` ${p.constraint}${v} **MANIFEST-ASSERTED**${desc}`;
        })
        .join("\n")
    : "<!-- MANIFEST has no validation_predicates. The structured form is optional; the plain-text validations above are still authoritative. -->";

  const exportBlock = exports_.length
    ? exports_.map(e => `- ${e} **MANIFEST-ASSERTED**`).join("\n")
    : "<!-- MANIFEST has no exports declared. CODE-INFERRED: walk IMPORT_EXPORT. -->";

  const importBlock = imports.length
    ? "\n## Imports (carry-over from manifest)\n\n" + imports.map(i => `- ${i} **MANIFEST-ASSERTED**`).join("\n") + "\n"
    : "";

  const signalBlock = signals.length
    ? signals.map(s => `- ${s} **MANIFEST-ASSERTED**`).join("\n")
    : "<!-- MANIFEST has no promotion signals declared. INTERVIEW-REQUIRED. -->";

  return `# Promotion plan: ${manifest.name}

**Source:** \`${sourcePath}\`
**Manifest version:** ${manifest.version}
**Date:** ${today}
**Generated by:** \`tools/promote.mjs\` — fill in the CODE-INFERRED and
INTERVIEW-REQUIRED sections by hand. Run \`prompts/promote-flatpack.md\`
in your head while you do.

Every claim in this plan is labelled with one of three confidence tiers:

- **MANIFEST-ASSERTED** — from the Flatpack's manifest. Trust it.
- **CODE-INFERRED** — to be extracted by reading the JS. Reliable for
  behaviour; worth a second pass with the user.
- **INTERVIEW-REQUIRED** — the Flatpack does not answer this. Ask
  the user during the promotion conversation.

---

## Why this is being promoted **INTERVIEW-REQUIRED**

<!-- INTERVIEW-REQUIRED:
     Which trigger fired? Who is now involved? Cite the signal
     from the manifest below that matches the user's situation. -->

## Archetype and recipe mapping

Archetype (from manifest): \`${archetype}\` **MANIFEST-ASSERTED**

Recommended Baseplate recipes (composed):

<!-- INTERVIEW-REQUIRED:
     Pick recipes from Baseplate's recipe set that compose to cover
     this archetype. See docs/archetypes.md (Flatpack-side hints) and
     Baseplate's docs/flatpack-archetype-to-recipe-map.md (canonical)
     when available. -->

Gaps not covered by any recipe:

<!-- INTERVIEW-REQUIRED:
     What does this Flatpack do that no Baseplate recipe currently
     provides? That code is yours to write. -->

## Entities

${entityBlock}

<!-- CODE-INFERRED:
     Are there entities the Flatpack uses implicitly that the manifest
     does not list? Read SCHEMA and STATE in the original file. -->

## Roles **INTERVIEW-REQUIRED**

<!-- INTERVIEW-REQUIRED:
     Who can do what in the Baseplate version? Common starts: Admin,
     Reviewer. Consider whether a read-only Reporter role is needed. -->

## Required features

| Feature | Tier | Notes |
|---|---|---|
| Persistent storage for entities above | MANIFEST-ASSERTED | Implied by entities |
| Field-level validation per manifest | MANIFEST-ASSERTED | See validations below |
| Each export as an endpoint or job | MANIFEST-ASSERTED | See exports below |
| Auth (named users + login) | INTERVIEW-REQUIRED | Likely \`admin-users\` recipe |
| Audit log | INTERVIEW-REQUIRED | Likely \`audit-log\` recipe |
| Admin screens | INTERVIEW-REQUIRED | What does the team need to see? |

## Validation rules (carry-over from manifest)

${validationBlock}

### Structured form (validation_predicates)

${predicateBlock}

<!-- CODE-INFERRED:
     Are there additional validation rules in the file's
     validate() / validateRow() function that the manifest does not
     name? Walk VALIDATION. -->

## Exports (carry-over from manifest)

${exportBlock}
${importBlock}
## UI / screens **CODE-INFERRED**

<!-- CODE-INFERRED:
     Walk the original file's HTML region. Each major screen / panel
     becomes a candidate screen in the Baseplate UI. -->

## Test cases to carry over **CODE-INFERRED**

<!-- CODE-INFERRED:
     Open the original Flatpack's FLATPACK:TEST_CASES region. Every
     name there becomes a Baseplate unit-test target. List them here
     with their target module. -->

## Promotion signals (from manifest)

${signalBlock}

## Open questions for the user **INTERVIEW-REQUIRED**

<!-- INTERVIEW-REQUIRED:
     Decisions the Flatpack does not constrain but the Baseplate
     project does need. Typical:
     - How are batches / records approved?
     - Who needs read access vs write?
     - Are there override flows for validation errors?
     - Does any export need to feed into another system?
     - What is multi-tenancy expectation? -->

## What is explicitly out of scope **INTERVIEW-REQUIRED**

<!-- INTERVIEW-REQUIRED:
     What did the Flatpack not do that the user has not asked for
     either? Naming non-goals up front saves scope creep. -->

## Hand-off

Once approved:

1. Open a new Baseplate project.
2. Copy \`${sourcePath}\` (and any sample data files) into the new
   project's \`reference/\` directory — preserve the Flatpack alive.
3. Apply the Baseplate recipes named above.
4. Carry the validation rules and test cases into the new project.
5. Once running, verify against the manifest with
   \`tools/verify-promotion.mjs\` (when available on the Baseplate side).
6. Keep the Flatpack reachable until parity is verified.
`;
}

function main() {
  const argv = process.argv.slice(2);
  if (!argv.length || argv.includes("--help") || argv.includes("-h")) {
    console.error("Usage: node tools/promote.mjs <path/to/flatpack.html> [--out plan.md]");
    process.exit(2);
  }
  const outIdx = argv.indexOf("--out");
  const outPath = outIdx >= 0 ? argv[outIdx + 1] : null;
  const filePath = argv.find(a => !a.startsWith("--") && a !== outPath);
  if (!filePath) {
    console.error("No input file given.");
    process.exit(2);
  }
  const abs = path.resolve(filePath);
  if (!fs.existsSync(abs)) {
    console.error(`File not found: ${abs}`);
    process.exit(2);
  }
  let manifest;
  try { manifest = readManifest(abs); }
  catch (e) { console.error(e.message); process.exit(1); }

  // Use the path as the user typed it (relative) for readability in the plan.
  const plan = renderPlan(manifest, filePath);

  if (outPath) {
    fs.writeFileSync(outPath, plan);
    console.error(`Wrote ${plan.split("\n").length} lines to ${outPath}.`);
  } else {
    process.stdout.write(plan);
  }
}

main();
